name: Download_and_Merge_Rules

on:
  schedule:
    - cron: "0 0 * * *" # 每天0点执行
  workflow_dispatch:

jobs:
  download_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Download Files
        run: |
          # 下载第一个链接中的内容并保存到 NoAppDownload.txt
          curl -L -o NoAppDownload.txt https://cdn.jsdelivr.net/gh/Noyllopa/NoAppDownload@master/NoAppDownload.txt
          # 下载第二个链接中的内容并保存到 mv.txt
          curl -L -o mv.txt https://cdn.jsdelivr.net/gh/xinggsf/Adblock-Plus-Rule@master/mv.txt
      
      - name: Create Branch and Merge Files
        run: |
          # 创建一个名为 urle 的新分支
          git checkout -b urle
          # 合并 NoAppDownload.txt 和 mv.txt 的内容到 urle.txt
          cat NoAppDownload.txt mv.txt > urle.txt
          # 添加、提交和推送更改到远程仓库
          git add urle.txt
          git commit -m "Merge NoAppDownload.txt and mv.txt into urle.txt"
          git push -u origin urle
